### ISSUE TITLE
Describe what Integrating with KubeVirt means

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/pepr-legacy#3]
In order to facilitate the integration of VM deployments with BigBang, a description of the steps and processes that need to occur are needed.

**Comment by runyontr** [comment]
https://kyverno.io/policies/kubevirt/add-services/add-services/

Found this policy in Kyverno's list.  Not sure if it's relevant

**Comment by mikevanhemert** [comment]
I don't think this is a perfect fit for all VM use cases but it provides a great template for automating VM access. It could be adapted for serial console or VNC
